highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Nicholas A Kovacs's Resume
name: Nicholas Attila Kovacs
website: nicholasakovacs.github.io
website_full: https://www.nicholasakovacs.github.io
github: NicholasAKovacs
twitter: NAttilaKovacs
address:
  postcode: Structural Bioinformticist
  city: Atlanta, Ga
  country: USA

# needed for travis-ci build
exclude: [vendor]
